### ISSUE TITLE
Packagist not synchronized

### ISSUE THREAD

**Issue by Rvanlaak** [asposeforcloud/asposesymfony#5]
https://packagist.org/packages/aspose/cloud-bundle

It still has a delay, so is not synchronized correctly. This way Composer will keep throwing exceptions while installing a new version.

**Comment by masood-anwer** [comment]
Issue was due to user rights and fixed it. Please check it and confirm.

**Comment by Rvanlaak** [comment]
Confirmed proper synchronization. The Github hook is working. Closing issue.
